name: Deploy Root Project to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload everything from the root, excluding other project folders and .github
          # This pattern might need adjustment if you have other top-level files/folders not part of the root project
          path: |
            ./
            !first web development code/
            !my Bookmarks/
            !web development 3/
            !web development 4/
            !web development 5/
            !web development 6/
            !.github/
            !README.md 
            # Add other top-level folders/files to exclude if they are not part of the root deployment

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
