name: Lighthouse Performance Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli serve
      - name: Run Lighthouse CI
        run: |
          npx serve -s . &
          sleep 5
          lhci autorun --collect.url=http://localhost:5000/index.html || true
