name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true
